title: Greta Tanudjaja # your name (or website title) here
logo: "images/11825621_10205838349335364_5170882685005430622_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Looking to switch full time job as cost estimator in the US into becoming a software developer/programmer in Germany.<br>
  <br><br>
  <br>Will graduate in Nov 2020 with a second Bachelor's degree in Information Technology from University of Massachussets Lowell. GPA = 4.0 (so far).<br>
  <a href="https://www.linkedin.com/in/greta1993/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
