title: Greta Tanudjaja # your name (or website title) here
logo: "images/11825621_10205838349335364_5170882685005430622_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Soon to graduate with a second Bachelor's degree in Information Technology from University of Massachussets Lowell. Have 4.0. GPA so far.
  <br><br>
  Aspiring software developer/programmer looking to find new job opportunities in Germany.
  <br><br>
  <a href="https://www.linkedin.com/in/greta1993/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
